os:
  - linux
  - osx
language: java
jdk:
  - openjdk10
  - openjdk11
branches:
  only:
    - dev
before_script:
  - cd $WORKDIR
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test -B
